### ISSUE TITLE
Slide Ads Error Search function

### ISSUE THREAD

**Issue by sanjayaharshana** [Enspirer/TPR#27]
http://localhost:8000/search_result_filter/key_name/max_price/min_price/commercial/transaction_type/property_type/beds/baths/land_size/listed_since/building_type/open_house/zoning_type/units/building_size/farm_type/parking_type

![image](https://user-images.githubusercontent.com/17973608/129707156-bd5b01c6-8c8e-4072-9930-68e791daae36.png)

**Comment by imzajjithvedha** [comment]
Fixed
