### ISSUE TITLE
Some Improvment and Bugs on Search Result

### ISSUE THREAD

**Issue by sanjayaharshana** [Enspirer/TPR#5]
![image](https://user-images.githubusercontent.com/17973608/129508971-074cbb87-28aa-4ab5-9780-2286a5accaff.png)

> Favorite Buttion Not Working, 

> Currency Not Showing

> Email algin issue,

> showing some static Data

**Comment by imzajjithvedha** [comment]
Currency fixed.
Email align issue fixed.
Removed static data.

I changed the condition for beds and baths. Please check it sir

**Comment by imzajjithvedha** [comment]
Favorite button task is pending

**Comment by imzajjithvedha** [comment]
Fixed
