### ISSUE TITLE
Search Function Not Working

### ISSUE THREAD

**Issue by sanjayaharshana** [Enspirer/TPR#6]
![image](https://user-images.githubusercontent.com/17973608/129509184-4f0b2f05-a7cc-42ce-9fe5-e31acf1d4d29.png)

http://localhost:8000/search_result_filter/key_name/max_price/min_price/commercial/transaction_type/property_type/beds/baths/land_size/listed_since/building_type/open_house/zoning_type/units/building_size/farm_type/parking_type

Search Function Not Working

**Comment by imzajjithvedha** [comment]
Fixed
